// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdKZYoB6qKYZ9fnWd1Xw6NPj-KUc6AA60',
    appId: '1:501189281670:android:bde5a9494492987cd90e07',
    messagingSenderId: '501189281670',
    projectId: 'ecommerce-app-27b8a',
    storageBucket: 'ecommerce-app-27b8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1lZg3fATgwMyVBBO6TFOfude7KUCGyh8',
    appId: '1:501189281670:ios:79bd94ed01109675d90e07',
    messagingSenderId: '501189281670',
    projectId: 'ecommerce-app-27b8a',
    storageBucket: 'ecommerce-app-27b8a.firebasestorage.app',
    androidClientId: '501189281670-s7qnh9klk9k1gtrjknc4umsi0qq4bic5.apps.googleusercontent.com',
    iosClientId: '501189281670-bdk2lham2oec7cj8vb6f6a89nr3krfut.apps.googleusercontent.com',
    iosBundleId: 'com.example.myecommerceapp',
  );
}
